### ISSUE TITLE
Code does not have a license

### ISSUE THREAD

**Issue by redstrate** [mystchonky/kontrast-rs#3]
The QML stuff is attributed and is clearly licensed, but the Rust code is not. That should probably be fixed :)

**Comment by dphaldes** [comment]
Can I use the same license as upstream? The rust code is almost 1:1 translation, so it should have the same license if it allows it

**Comment by redstrate** [comment]
> Can I use the same license as upstream? The rust code is almost 1:1 translation, so it should have the same license if it allows it

Yeah I think that's fine, IMO I would consider this a completely different body of work but there's pretty much no reason to license it any different
